version: 2
jobs:
  test:
    docker:
      - image: cimg/go:1.19
        environment:
          GOMAXPROCS: 2
    steps:
      - checkout
      - run:
          name: Avoid hosts unknown for github
          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: Fetch golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
      - run:
          name: Install dependencies
          command: |
            make setup
            go get ./...
      - run:
          name: lint
          command: make lint
      - run: make test
      - run:
          name: Report code coverage
          command: bash <(curl -s https://codecov.io/bash) -t "172993e7-77a9-4aad-a9ef-6319b1a2d51d" || echo "Coverage not reported"

workflows:
  version: 2
  test:
    jobs:
      - test